services:
  tubearchivist:
    container_name: tubearchivist
    image: bbilly1/tubearchivist
    ports:
      - "8000:8000"
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_CON=redis://archivist-redis:6379
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=http://192.168.100.195:8000
      - TA_USERNAME=admin
      - TA_PASSWORD=admin
      - ELASTIC_PASSWORD=admin
      - TZ=Asia/Kolkata
    restart: unless-stopped
    volumes:
      - ./data/media:/youtube
      - ./data/cache:/cache
    depends_on:
      - archivist-es
      - archivist-redis

  archivist-redis:
    container_name: archivist-redis
    image: redis:7
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

  archivist-es:
    container_name: archivist-es
    image: bbilly1/tubearchivist-es
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=admin
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

